config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [ :new, :create, :index ]
  resources :addresses
  resource :session, only: [ :new, :create, :destroy ]
  resources :passwords, param: :token
  resources :products
  resources :registrations, only: [ :new, :create ]
  resources :carts, only: [ :show ] do
    post "remove"
  end
  post "carts/add", to: "carts#add", as: "cart_add"

  namespace :auth do
    scope "/google" do
      get "authenticate", to: "google#authenticate", as: "google"
      get "callback", to: "google#callback", as: "google_callback"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "products#index"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :address
  belongs_to :cart

  enum :status, {
    pending: "pending",
    awaiting_payment: "awaiting_payment",
    paid: "paid",
    failed: "failed",
    processing: "processing",
    shipped: "shipped",
    canceled: "canceled",
    finished: "finished"
  }
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Current.user.orders
  end

  def new
    @order = Order.new
    @addresses = Current.user.addresses
  end

  def create
    user = Current.user
    cart = user.active_cart

    @order = Order.new(order_params.merge(user: user, cart: cart))

    ActiveRecord::Base.transaction do
      cart.cart_items.each do |item|
        item.update_product_stock!
      end
      cart.ordered!
      @order.processing!

      redirect_to root_path, notice: "Order is being processed right now!!! =)"
    rescue
      redirect_to cart_path(user.active_cart), alert: "Could not complete order =("
    end
  end

  private

  def order_params
    params.require(:order).permit(:address_id, :cart_id, :user_id)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<% content_for :title, "Orders" %>

<h1>Orders</h1>

<div id="orders" class="d-flex flex-column">
  <% @orders.each do |order| %>
    <div class="d-inline-flex border rounded m-2 p-2">
      <p>
        <strong> Order number: </strong>
        <%= order.id %>
      </p>
      <p>
        <strong> status: </strong>
        <%= order.status %>
      </p>
    </div>
  <% end %>
</div>

app/views/orders/new.html.erb
<h1>Checkout</h1>

<p> Selecione endereco para entrega </p>
<%= button_to "Add new address", new_address_path, method: :get %>

<% if @addresses %>
<%= form_with(model: @order, url: orders_path) do |form| %>
  <%# form.hidden_field :cart_id, value: Current.user.active_cart.id %>
  <%# form.hidden_field :user_id, value: Current.user.id %>
  <% @addresses.each do |address| %>
    <div class="form-check m-4">
      <input
        class="form-check-input"
        type="radio"
        name="order[address_id]"
        value="<%= address.id %>"
        <%= "checked" if address.primary_address %>
      >
      <label class="form-check-label" for="address-radio">
        <%= render 'addresses/address', address: address %>
      </label>
      <%= link_to "Edit this address", edit_address_path(address) %>
    </div>
  <% end %>
  <%= form.submit "Order" %>
<% end %>
<% end %>