config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [ :new, :create, :index ]
  resources :addresses
  resource :session, only: [ :new, :create, :destroy ]
  resources :passwords, param: :token
  resources :products
  resources :registrations, only: [ :new, :create ]
  resources :carts, only: [ :show ] do
    post "remove"
  end
  post "carts/add", to: "carts#add", as: "cart_add"

  namespace :auth do
    scope "/google" do
      get "authenticate", to: "google#authenticate", as: "google"
      get "callback", to: "google#callback", as: "google_callback"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "products#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  has_many :products, through: :cart_items
  has_one :order

  validates_presence_of :status

  enum :status, { active: "active", ordered: "ordered" }

  def total
    cart_items.pluck(:price).sum
  end

  def update_cart_item(product, quantity)
    cart_item = cart_items.find_by(product:)

    if cart_item && quantity > 0
      cart_item.update!(quantity:, price: product.price * quantity)
    elsif quantity <= 0
      cart_item.destroy!
    else
      cart_items.create!(product:, quantity:, price: product.price * quantity)
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart

  def show; end

  def add
    product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    @cart.update_cart_item(product, quantity)
  end

  def remove
    CartItem.find_by(id: params[:id]).destroy
  end

  private

  def set_cart
    @cart = Current.user.active_cart
  end
end

app/views/carts/_cart_items.html.erb
<% @cart.cart_items.each do |item| %>
  <% product = item.product %>
  <div id="<%= "cart-#{product.id}" %>">
  <div class="d-inline-flex justify-contentt-around">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= item.quantity %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= item.price %>
  </p>
    <%= form_with(url: cart_add_path) do |form| %>
    <%= form.hidden_field :id, value: product.id %>
    <%= form.number_field :quantity, value: item.quantity, min: 0, max: product.quantity%>
    <%= form.submit "update quantity"%>
  <% end %>

  <%= form_with(url: cart_remove_path(@cart)) do |form| %>
    <%= form.hidden_field :id, value: item.id %>
    <%= form.submit "Remove item"%>
  <% end %>

  </div>
<% end %>

app/views/carts/show.html.erb
<%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
<%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %>

<h1> Cart </h1>
<h2> Cart for user <%= Current.user.email_address %> </h2>

<%= render 'cart_items', local: @cart %>
<p>
  <strong> Total: </strong>
  <%= @cart.total %>
</p>

<%= button_to 'Checkout', new_order_path, method: :get %>