config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [ :new, :create, :index ]
  resources :addresses
  resource :session, only: [ :new, :create, :destroy ]
  resources :passwords, param: :token
  resources :products
  resources :registrations, only: [ :new, :create ]
  resources :carts, only: [ :show ] do
    post "remove"
  end
  post "carts/add", to: "carts#add", as: "cart_add"

  namespace :auth do
    scope "/google" do
      get "authenticate", to: "google#authenticate", as: "google"
      get "callback", to: "google#callback", as: "google_callback"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images
  has_many :cart_items
  has_many :carts, through: :orderables

  validates_presence_of :name, :description, :quantity, :price
  validates :quantity, :price, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.expect(product: [ :name, :description, :quantity, :price, images: [] ])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price, step: "0.01" %>
  </div>

  <div>
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= product.quantity %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price.to_s %>
  </p>

  <p>
    <% product.images.each do |image| %>
      <%= image_tag image, class: "h-25 w-25" %>
    <% end %>
  </p>

  <%= form_with(url: cart_add_path) do |form| %>
    <%= form.hidden_field :id, value: product.id %>
    <%= form.number_field :quantity, value: 0, min: 1, max: product.quantity %>
    <%= form.submit "Add to cart"%>
  <% end %>
</div>

app/views/products/edit.html.erb
<% content_for :title, "Editing product" %>

<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
<%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %>

<% content_for :title, "Products" %>

<h1>Products</h1>

<div class="container" id="products">
  <div class="row row-cols-5 justify-content-center">
  <% @products.each do |product| %>
    <div class="card col m-2" style="width: 18rem;">
      <%= image_tag product.images.first, class: "card-img-top", alt: "Main product image"%>
      <div class="card-body">
        <h5 class="card-title"><%= product.name %></h5>
        <p class="card-text">R$ <%= product.price%></p>
        <a href="#" class="btn btn-primary">Add to cart</a>
        <a href="<%= product_path(product) %>" class="card-link">Details</a>
      </div>
    </div>
  <% end %>
  </div>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<% content_for :title, "New product" %>

<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>