config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [ :new, :create, :index ]
  resources :addresses
  resource :session, only: [ :new, :create, :destroy ]
  resources :passwords, param: :token
  resources :products
  resources :registrations, only: [ :new, :create ]
  resources :carts, only: [ :show ] do
    post "remove"
  end
  post "carts/add", to: "carts#add", as: "cart_add"

  namespace :auth do
    scope "/google" do
      get "authenticate", to: "google#authenticate", as: "google"
      get "callback", to: "google#callback", as: "google_callback"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "products#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%# stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-secondary min-vh-100">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">e-Shop</a>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
          <% if authenticated? %>
            <li class="nav-item">
              <%= button_to "Logout", session_path, method: :delete, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= orders_path %>">Orders</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= cart_path(Current.user.active_cart) %>">Cart</a>
            </li>
          <% else %>
            <a class="nav-link active" aria-current="page" href="<%= new_session_path %>">Login</a>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container body-height bg-light">
      <%= yield %>
    </div>
  </body>
</html>